/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#7ffc97",
        "primary-container": "#00873a",
        "inverse-surface": "#2d3133",
        "secondary-fixed": "#6bff8f",
        "outline-variant": "#bdcaba",
        "surface-container-highest": "#e0e3e5",
        "inverse-primary": "#62df7d",
        "surface-container-low": "#f2f4f6",
        "on-secondary": "#ffffff",
        "surface": "#f7f9fb",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed": "#002109",
        "background": "#f7f9fb",
        "primary": "#006b2c",
        "secondary": "#006e2f",
        "on-background": "#191c1e",
        "on-error": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "tertiary": "#466252",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#042014",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#3e4a3d",
        "on-surface": "#191c1e",
        "surface-container": "#eceef0",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed-variant": "#005321",
        "on-primary-container": "#f7fff2",
        "surface-tint": "#006e2d",
        "primary-fixed-dim": "#62df7d",
        "on-primary-fixed": "#002109",
        "tertiary-fixed": "#caead6",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f6fff6",
        "outline": "#6e7b6c",
        "secondary-fixed-dim": "#4ae176",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#005320",
        "on-secondary-container": "#007432",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#afceba",
        "surface-variant": "#e0e3e5",
        "secondary-container": "#6bff8f",
        "tertiary-container": "#5e7b6a",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed-variant": "#314d3e",
        "on-primary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "12px",
        "xs": "4px",
        "gutter": "24px",
        "base": "8px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "lg": "48px",
        "xl": "80px",
        "md": "24px"
      },
      fontFamily: {
        "body-md": ["Manrope", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "display-lg": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-sm": ["Manrope", "sans-serif"],
        "display-lg-mobile": ["Manrope", "sans-serif"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "label-sm": ["12px", { "lineHeight": "1", "fontWeight": "600" }],
        "headline-md": ["30px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-sm": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "display-lg-mobile": ["36px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }]
      },
      maxWidth: {
        "xs": "20rem",
        "sm": "24rem",
        "md": "28rem",
        "lg": "32rem",
        "xl": "36rem",
      }
    },
  },
  plugins: [],
}
